// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// unnamed API: Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/goadesign/goa/design/apidsl
// --out=$(GOPATH)\src\goa
// --version=v1.3.1

package app
